"""
Vector embeddings client for generating embeddings using Amazon Titan Embeddings.
Based on the AWS blog post implementation for RAG systems.
"""

import os
import json
import logging
import boto3
from typing import List, Dict, Any, Optional
from botocore.exceptions import ClientError
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

class EmbeddingsClient:
    """Client for generating vector embeddings using Amazon Titan Embeddings."""
    
    def __init__(self):
        """Initialize the embeddings client."""
        self.aws_region = os.getenv("AWS_REGION", "us-east-1")
        self.model_id = os.getenv("EMBEDDINGS_MODEL_ID", "amazon.titan-embed-text-v1")
        
        # Initialize Bedrock client
        self.client = boto3.client("bedrock-runtime", region_name=self.aws_region)
        
        logger.info(f"Embeddings client initialized with model: {self.model_id}")
    
    def generate_embedding(self, text: str) -> Optional[List[float]]:
        """
        Generate a vector embedding for the given text.
        
        Args:
            text: Text to generate embedding for
            
        Returns:
            List of float values representing the embedding vector, or None if failed
        """
        try:
            # Prepare the request body for Titan Embeddings
            body = json.dumps({
                "inputText": text
            })
            
            # Make the request to Bedrock
            response = self.client.invoke_model(
                modelId=self.model_id,
                body=body,
                contentType="application/json"
            )
            
            # Parse the response
            response_body = json.loads(response['body'].read())
            embedding = response_body['embedding']
            
            logger.info(f"Successfully generated embedding with {len(embedding)} dimensions")
            return embedding
            
        except ClientError as e:
            logger.error(f"Bedrock client error generating embedding: {e}")
            return None
        except Exception as e:
            logger.error(f"Unexpected error generating embedding: {e}")
            return None
    
    def generate_embeddings_batch(self, texts: List[str]) -> Dict[str, Optional[List[float]]]:
        """
        Generate embeddings for multiple texts.
        
        Args:
            texts: List of texts to generate embeddings for
            
        Returns:
            Dictionary mapping text to embedding vector
        """
        results = {}
        
        for text in texts:
            embedding = self.generate_embedding(text)
            results[text] = embedding
        
        successful_embeddings = sum(1 for emb in results.values() if emb is not None)
        logger.info(f"Generated {successful_embeddings}/{len(texts)} embeddings successfully")
        
        return results
    
    def get_embedding_dimension(self) -> int:
        """
        Get the dimension of embeddings generated by the model.
        Titan Embeddings v1 generates 1536-dimensional vectors.
        
        Returns:
            Embedding dimension
        """
        return 1536
    
    def validate_embedding(self, embedding: List[float]) -> bool:
        """
        Validate that an embedding vector is properly formatted.
        
        Args:
            embedding: Embedding vector to validate
            
        Returns:
            True if valid, False otherwise
        """
        if not embedding or not isinstance(embedding, list):
            return False
        
        # Check if all elements are numbers
        try:
            float_embedding = [float(x) for x in embedding]
            return len(float_embedding) == self.get_embedding_dimension()
        except (ValueError, TypeError):
            return False
