#!/usr/bin/env python3
"""
Runs the code generated by the code generator using the dataset provided in the paper (if provided)
"""

import os
import sys
import subprocess
import argparse
from pathlib import Path

def test_generated_code(code_file: str, install_deps: bool = False):
    """
    Test a generated PyTorch code file
    
    Args:
        code_file: Path to the generated .py file
        install_deps: Whether to try installing dependencies first
    """
    code_path = Path(code_file)
    
    if not code_path.exists():
        print(f"Error: File {code_file} not found")
        return False
    
    print(f"Testing generated code: {code_path.name}")
    print("=" * 60)
    
    with open(code_path, 'r') as f:
        code_content = f.read()
    
    # Check if contains dataset preparation function
    has_dataset_prep = any(keyword in code_content.lower() for keyword in [
        'download_dataset', 'prepare_dataset', 'load_data', 'get_dataset'
    ])
    
    if has_dataset_prep:
        print("Found dataset preparation function")
    else:
        print("Warning: No dataset preparation function found")
    
    # Try running code
    print(f"\nRunning {code_path.name}...")
    print("-" * 60)
    
    try:
        result = subprocess.run(
            [sys.executable, str(code_path)],
            capture_output=True,
            text=True,
            timeout=300  # 5 minute timeout
        )
        
        print(result.stdout)
        
        if result.returncode == 0:
            print("-" * 60)
            print("Code executed successfully")
            return True
        else:
            print("-" * 60)
            print("Code execution failed:")
            print(result.stderr)
            return False
            
    except subprocess.TimeoutExpired:
        print("⏱Code execution timed out (5 minutes)")
        print("This might be normal for training - check if training started successfully")
        return False
    except Exception as e:
        print(f"Error running code: {e}")
        return False

def list_generated_code(directory: str = "generated_code"):
    """List all generated code files."""
    code_dir = Path(directory)
    
    if not code_dir.exists():
        print(f"Directory {directory} not found")
        return
    
    py_files = sorted(code_dir.glob("*.py"))
    
    if not py_files:
        print(f"No generated Python files found in {directory}")
        return
    
    print(f"Generated code files in {directory}:")
    print("=" * 60)
    
    for i, py_file in enumerate(py_files, 1):
        # Get metadata if exists
        metadata_file = py_file.with_suffix('.json')
        if '_metadata' not in py_file.stem:
            metadata_file = py_file.parent / f"{py_file.stem}_metadata.json"
        
        size_kb = py_file.stat().st_size / 1024
        
        print(f"\n{i}. {py_file.name}")
        print(f"   Size: {size_kb:.1f} KB")
        
        if metadata_file.exists():
            import json
            with open(metadata_file) as f:
                meta = json.load(f)
                print(f"   Paper: {meta.get('paper_title', 'Unknown')[:60]}...")
                print(f"   Generated: {meta.get('generated_at', 'Unknown')}")

def main():
    parser = argparse.ArgumentParser(
        description='Test runner for generated PyTorch code'
    )
    
    parser.add_argument(
        'command',
        choices=['test', 'list'],
        help='Command to run (test or list)'
    )
    
    parser.add_argument(
        '--file',
        help='Path to generated code file (for test command)'
    )
    
    parser.add_argument(
        '--dir',
        default='generated_code',
        help='Directory containing generated code (default: generated_code)'
    )
    
    parser.add_argument(
        '--install-deps',
        action='store_true',
        help='Try to install dependencies before testing'
    )
    
    args = parser.parse_args()
    
    if args.command == 'list':
        list_generated_code(args.dir)
    
    elif args.command == 'test':
        if not args.file:
            print("Error: --file argument required for test command")
            parser.print_help()
            sys.exit(1)
        
        success = test_generated_code(args.file, args.install_deps)
        sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()
