#!/usr/bin/env python3
"""
All code that gets generated by Lambda + code_generator gets stored in S3. This script gets all the code and metadata from S3 and sends it to your generated_code/ folder.
"""

import boto3
import sys
import json
from pathlib import Path
from datetime import datetime

s3 = boto3.client('s3')
BUCKET = 'papers-code-artifacts'
OUTPUT_DIR = 'generated_code'

def list_papers_with_metadata():
    """List all papers with generated code and their metadata."""
    response = s3.list_objects_v2(Bucket=BUCKET, Delimiter='/')
    
    if 'CommonPrefixes' not in response:
        print("No generated code found in S3")
        return []
    
    papers = []
    print("\nPapers with generated code:")
    print("=" * 80)
    
    for idx, prefix in enumerate(response['CommonPrefixes'], 1):
        paper_id = prefix['Prefix'].rstrip('/')
        
        try:
            metadata_key = f"{paper_id}/metadata.json"
            meta_response = s3.get_object(Bucket=BUCKET, Key=metadata_key)
            metadata = json.loads(meta_response['Body'].read().decode('utf-8'))
            title = metadata.get('paper_title', 'Unknown')
            authors = metadata.get('paper_authors', [])
            author_str = ', '.join(authors[:2]) if isinstance(authors, list) else str(authors)
            if len(authors) > 2:
                author_str += f" +{len(authors)-2} more"
            
            print(f"{idx}. {title[:60]}")
            print(f"   Authors: {author_str[:60]}")
            print(f"   ID: {paper_id}")
            print()
        except:
            print(f"{idx}. Paper ID: {paper_id}")
            print()
        
        papers.append(paper_id)
    
    return papers

def download_paper_code(paper_id: str):
    """Download code and metadata for a specific paper."""
    Path(OUTPUT_DIR).mkdir(exist_ok=True)
    
    # Download code
    code_key = f"{paper_id}/code.py"
    metadata_key = f"{paper_id}/metadata.json"
    
    try:
        # Get metadata first (just to create nice file name)
        try:
            meta_response = s3.get_object(Bucket=BUCKET, Key=metadata_key)
            metadata = json.loads(meta_response['Body'].read().decode('utf-8'))
            title = metadata.get('paper_title', 'unknown')
            # Clean title for filename
            safe_title = "".join(c for c in title if c.isalnum() or c in (' ', '-', '_')).rstrip()
            safe_title = safe_title.replace(' ', '_')[:50]
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{safe_title}_{timestamp}.py"
            metadata_filename = f"{safe_title}_{timestamp}_metadata.json"
        except:
            filename = f"{paper_id}.py"
            metadata_filename = f"{paper_id}_metadata.json"
        
        # Download code
        code_path = Path(OUTPUT_DIR) / filename
        s3.download_file(BUCKET, code_key, str(code_path))
        print(f"Downloaded code to: {code_path}")
        
        # Download metadata
        try:
            metadata_path = Path(OUTPUT_DIR) / metadata_filename
            s3.download_file(BUCKET, metadata_key, str(metadata_path))
            print(f"Downloaded metadata to: {metadata_path}")
        except:
            print("Metadata not available")
        
        return True
        
    except Exception as e:
        print(f"Error downloading: {e}")
        return False

def main():
    print("Download Generated Code from S3")
    print("=" * 80)
    
    # List all papers
    papers = list_papers_with_metadata()
    
    if not papers:
        return
    
    # Allows you to choose which paper code to download by ID
    try:
        choice = input(f"\nEnter number (1-{len(papers)}) or 'all' to download all: ").strip()
        
        if choice.lower() == 'all':
            print(f"\nDownloading all {len(papers)} papers...")
            for paper_id in papers:
                download_paper_code(paper_id)
            print(f"\nDownloaded {len(papers)} papers to {OUTPUT_DIR}/")
        else:
            idx = int(choice) - 1
            if 0 <= idx < len(papers):
                paper_id = papers[idx]
                print(f"\nDownloading paper: {paper_id}")
                download_paper_code(paper_id)
            else:
                print("Invalid choice")
    except KeyboardInterrupt:
        print("\n\nCancelled")
    except ValueError:
        print("Invalid input")

if __name__ == "__main__":
    main()

